apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jenkins-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
  - name: ng-2
    instanceType:  t2.micro
    desiredCapacity: 2
